// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const postLabel: string;
export const postsContainer: string;
export const post: string;
