// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const toyContent: string;
export const imageContainer: string;
export const details: string;
